// Generated by gencpp from file i2c_communication/i2c.msg
// DO NOT EDIT!


#ifndef I2C_COMMUNICATION_MESSAGE_I2C_H
#define I2C_COMMUNICATION_MESSAGE_I2C_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace i2c_communication
{
template <class ContainerAllocator>
struct i2c_
{
  typedef i2c_<ContainerAllocator> Type;

  i2c_()
    : header()
    , raw(0)  {
    }
  i2c_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , raw(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _raw_type;
  _raw_type raw;





  typedef boost::shared_ptr< ::i2c_communication::i2c_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::i2c_communication::i2c_<ContainerAllocator> const> ConstPtr;

}; // struct i2c_

typedef ::i2c_communication::i2c_<std::allocator<void> > i2c;

typedef boost::shared_ptr< ::i2c_communication::i2c > i2cPtr;
typedef boost::shared_ptr< ::i2c_communication::i2c const> i2cConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::i2c_communication::i2c_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::i2c_communication::i2c_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace i2c_communication

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'i2c_communication': ['/home/ubuntu/project_theia/ws/src/i2c_communication/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::i2c_communication::i2c_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::i2c_communication::i2c_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::i2c_communication::i2c_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::i2c_communication::i2c_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::i2c_communication::i2c_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::i2c_communication::i2c_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::i2c_communication::i2c_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c70b01a642177dd8a27557273aacf98d";
  }

  static const char* value(const ::i2c_communication::i2c_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc70b01a642177dd8ULL;
  static const uint64_t static_value2 = 0xa27557273aacf98dULL;
};

template<class ContainerAllocator>
struct DataType< ::i2c_communication::i2c_<ContainerAllocator> >
{
  static const char* value()
  {
    return "i2c_communication/i2c";
  }

  static const char* value(const ::i2c_communication::i2c_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::i2c_communication::i2c_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint16 raw\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::i2c_communication::i2c_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::i2c_communication::i2c_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.raw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct i2c_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::i2c_communication::i2c_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::i2c_communication::i2c_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "raw: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.raw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // I2C_COMMUNICATION_MESSAGE_I2C_H
